### ISSUE TITLE
Реализовать расчет предполагаемого времени доставки посылки

### ISSUE THREAD

**Issue by Bogovesov** [internal-jew/deliver-it#12]
Реализовать метод `estimate` в классе `DeliveryTime` в модуле `logistics`.

**Comment by Vadym-Mitin** [comment]
Для полного решения этой задачи не хватает понимания как работает наш ФСМ - сколько состояний будет в каждом отделении (кстати это тоже надо реализовать) от этого и плясать + определиться что означает weight в классе Rout это километры или что то другое...

**Comment by Vadym-Mitin** [comment]
написан, есть к чему стремиться но по первой сойдет
