### ISSUE TITLE
Определить основные модели для User Story #1

### ISSUE THREAD

**Issue by internal-jew** [internal-jew/deliver-it#2]
В модуле `model` необходимо определить следующие сущности ([entities](https://habr.com/post/275599/)):

- `Sender`, отправитель;
  - одним из полей должен быть`SenderProfile`, [POJO *](https://ru.wikipedia.org/wiki/POJO) c основной информацией об отправителе: name, postal address, country ([справка](https://www.mkyong.com/java/display-a-list-of-countries-in-java/)).
- `TrackNumber`, трек-номер.
  - состоит из значения типа string.
- `Package`, посылка.
  - состоит из поля weight;

В дополнение к перечисленным моделям нужно определить следующие [value objects](https://habr.com/post/275599/):
- `SenderProfile`, `Name`, `PostalAddress` ([давайте использовать американский стандарт](https://blink.ucsd.edu/facilities/services/mail/international/addressing/index.html)), `Country` (основаный [на двузначных кодах](https://www.mkyong.com/java/display-a-list-of-countries-in-java/));
- `Weight`, вес (подумайте, из чего он может состоять);
- `Money`, деньги (реализуем как целое число, для простоты);
- `EstimatedDeliveryTime`, оценочное время доставки (внутри [LocalDate](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html)).

### Требования

1. Каждая модель должна наследовать класс `Entity` и, соответственно, иметь свой `EntityId`: TrackNumberId, PackageId, SenderId, etc;
2. Модели должны использовать value objects.
3. `PostalAddress` должен создавать только с помощью Builder.
4. Все `value objects` должны быть [immutable](https://code-examples.net/ru/q/6037d8), т.е. их можно создать, но нельзя изменить;
5. Разбитие по пакетам:
    - `com.alevel.deliverit.billing`: 
       - `Money`.
    - `com.alebel.deliverit.customers`: 
       - `Sender`;
       - `SenderProfile`;
       - `Package`;
       - `Country`;
       - `Weight`;
    - `com.alever.deliverit.logistics`:
       - `EstimatedDeliveryTime`;
       - `TrackNumber`;

**\*** `POJO` -- объект, состоящий только из приватных полей, с getters [ и setters].

**Comment by Vadym-Mitin** [comment]
Классы созданы, прошли первичный рефакторинг, не до конца понятно выполнил ли я задачу(Все value objects должны быть immutable, т.е. их можно создать, но нельзя изменить;)

**Comment by Vadym-Mitin** [comment]
https://nyc-brooklyn.ru/kak-pravilno-napisat-pochtovii-adres-amerika/
